### ISSUE TITLE
Data pre-processing Part - 1

### ISSUE THREAD

**Issue by Nish-19** [NJACKWinterOfCode/Credit-Card-Fraud-Detection#2]
# Todo 

* Ensuring all features are to scale
* Considering only essential features for the model.

**Comment by sakshamj74** [comment]
I would like to do this @Nish-19

**Comment by confifu** [comment]
Is only one person assigned to one issue ??  If not, then I am also interested in doing this. @Nish-19

**Comment by Nish-19** [comment]
@sakshamj74 can do it for keras_classification.py and @saturn660 can do it for random_forest.py
