### ISSUE TITLE
Applying upsampling in Keras_classification.py

### ISSUE THREAD

**Issue by sakshamj74** [NJACKWinterOfCode/Credit-Card-Fraud-Detection#5]
It is an imbalanced dataset so upsampling or downsampling can be performed for better results

**Comment by sakshamj74** [comment]
@Nish-19 can I work on this.

**Comment by Nish-19** [comment]
Yes, @sakshamj74. Please go ahead.

**Comment by sakshamj74** [comment]
@Nish-19 Please review #6

**Comment by sakshamj74** [comment]
@Nish-19  I have uploaded it again. Plz review #7

**Comment by confifu** [comment]
@Nish-19 What are the algos that we have to implement in keras? Other data processing steps?

**Comment by Nish-19** [comment]
@saturn660 one has to define a neural network that will do the classification task using keras api. 
You are free to use the pre-processing steps which you would want to.

**Comment by sakshamj74** [comment]
@Nish-19 I would like to work on neural network.
